### ISSUE TITLE
Problem with a .so file. Python 3.5, Mac OSX Sierra

### ISSUE THREAD

**Issue by GoldSloth** [unbit/foohid-py#5]
When ever I try and import foohid, I get an error:
(Tried it on 2.7.9 also, same problem)

![screen shot 2017-02-14 at 12 16 19](https://cloud.githubusercontent.com/assets/22482566/22928691/a9e92fe4-f2af-11e6-9033-ed893cb79be4.jpg)

I know this library is no longer maintained, but could someone please help me?

Thanks,

GolddolphinSKB-Fexcraftian

**Comment by TwistedBlizzard** [comment]
I have the same issue with 3.6.1 but 2.7.13 works fine.

**Comment by dwang733** [comment]
The reason is that PyString_FromString is a Python 2 method that doesn't work in Python 3. The most recent commit should have fixed this, so it should work for Python 2 and 3.

**Comment by GoldSloth** [comment]
Okay, I will try this, Thanks for your work!

**Comment by GoldSloth** [comment]
I can confirm this issue is now solved. Thanks for your help!

**Comment by dwang733** [comment]
Oh, btw, do you mind closing the issue? I can't seem to do it myself for some reason.
